import {GOOGLE_API_KEY, FIREBASE_API_KEY, FIREBASE_APP_ID, ANDROID_CLIENT_ID, IOS_CLIENT_ID, WEB_CLIENT_ID} from '@env'

const proAPI_KEYS = {
   GOOGLE_API_KEY, FIREBASE_API_KEY, FIREBASE_APP_ID, ANDROID_CLIENT_ID, IOS_CLIENT_ID, WEB_CLIENT_ID
}

export default proAPI_KEYS;